### ISSUE TITLE
New commands

### ISSUE THREAD

**Issue by megatron0001** [salasxd/multiworlds#3]
Can you add commands to add or remove servers,

When a user creates a world they get op on it,

such as this:

For admins:
/addworld "world name" "ip" "port" "other stuff optional"

For normal players:
/makeworld "worldname" (This would auto select the ip and port also other stuff)

/removeworld "worldname" (People are only allowed to remove servers they own, unless they are op)

**Comment by salasxd** [comment]
outdated version
